// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getHealth, getHealthDetailed, type Options, postSamplesPubsub } from '../sdk.gen';
import type { GetHealthData, GetHealthDetailedData, GetHealthDetailedResponse, GetHealthResponse, PostSamplesPubsubData, PostSamplesPubsubResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

export const getHealthOptions = (options?: Options<GetHealthData>) => queryOptions<GetHealthResponse, DefaultError, GetHealthResponse, ReturnType<typeof getHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHealthQueryKey(options)
});

export const getHealthDetailedQueryKey = (options?: Options<GetHealthDetailedData>) => createQueryKey('getHealthDetailed', options);

export const getHealthDetailedOptions = (options?: Options<GetHealthDetailedData>) => queryOptions<GetHealthDetailedResponse, DefaultError, GetHealthDetailedResponse, ReturnType<typeof getHealthDetailedQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHealthDetailed({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHealthDetailedQueryKey(options)
});

export const postSamplesPubsubMutation = (options?: Partial<Options<PostSamplesPubsubData>>): UseMutationOptions<PostSamplesPubsubResponse, DefaultError, Options<PostSamplesPubsubData>> => {
    const mutationOptions: UseMutationOptions<PostSamplesPubsubResponse, DefaultError, Options<PostSamplesPubsubData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postSamplesPubsub({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
