// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetHealthData, GetHealthDetailedData, GetHealthDetailedResponses, GetHealthResponses, PostSamplesPubsubData, PostSamplesPubsubResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

export const getHealthDetailed = <ThrowOnError extends boolean = false>(options?: Options<GetHealthDetailedData, ThrowOnError>) => (options?.client ?? client).get<GetHealthDetailedResponses, unknown, ThrowOnError>({ url: '/health/detailed', ...options });

export const postSamplesPubsub = <ThrowOnError extends boolean = false>(options?: Options<PostSamplesPubsubData, ThrowOnError>) => (options?.client ?? client).post<PostSamplesPubsubResponses, unknown, ThrowOnError>({
    url: '/samples/pubsub',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});
