// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:7315/' | (string & {});
};

export type DetailedHealthResponse = {
    status: string;
    version: string;
    environment: string;
    timestamp: string;
    durationMs: number | string;
    checks: Array<HealthCheckInfo>;
};

export type HealthCheckInfo = {
    name: string;
    status: string;
    durationMs: number | string;
};

export type HealthResponse = {
    status: string;
    timestamp: string;
};

export type PublishSamplePubSubRequest = {
    message: null | string;
    source: null | string;
};

export type PublishSamplePubSubResponse = {
    component: string;
    topic: string;
    eventId: string;
    publishedAtUtc: string;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * OK
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetHealthDetailedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/detailed';
};

export type GetHealthDetailedResponses = {
    /**
     * OK
     */
    200: DetailedHealthResponse;
};

export type GetHealthDetailedResponse = GetHealthDetailedResponses[keyof GetHealthDetailedResponses];

export type PostSamplesPubsubData = {
    body?: null | PublishSamplePubSubRequest;
    path?: never;
    query?: never;
    url: '/samples/pubsub';
};

export type PostSamplesPubsubResponses = {
    /**
     * OK
     */
    200: PublishSamplePubSubResponse;
};

export type PostSamplesPubsubResponse = PostSamplesPubsubResponses[keyof PostSamplesPubsubResponses];
